apiVersion: skaffold/v2beta4
kind: Config
deploy:
    kubectl:
        manifests:
            - ../k8s/common/*
            - ../k8s/dev/*
build:
    local:
        push: false
    artifacts:
        - image: rishabh75/billsplit-internal
          context: ../../
          docker:
              dockerfile: ../Dockerfiles/Dockerfile.main
          sync:
              manual:
                  - src: "src/**/*.js"
                    dest: .
        - image: rishabh75/billsplit-email
          context: ../../
          docker:
              dockerfile: ../Dockerfiles/Dockerfile.email
          sync:
              manual:
                  - src: "src/**/*.js"
                    dest: .
        - image: rishabh75/billsplit-email-cron
          context: ../../
          docker:
              dockerfile: ../Dockerfiles/Dockerfile.cron
          sync:
              manual:
                  - src: "src/**/*.js"
                    dest: .
        - image: rishabh75/billsplit-client
          context: ../../../bill-split-fe
          docker:
              dockerfile: ../Dockerfiles/Dockerfile.client
          sync:
              manual:
                  - src: "src/**/*.js"
                    dest: .
