# Build
FROM node:16-alpine as build
RUN mkdir /app
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

# Serve
FROM nginx:1.17
COPY --from=build /app/dist /usr/share/nginx/html
# CMD ["sh", "-c", "npm start"]

# FROM nginx:1.17
# COPY dist/ /usr/share/nginx/html