apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-svc
    annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    ingressClassName: nginx
    rules:
        - host: billsplit.app
          http:
              paths:
                  - path: /api/be/?(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: internal-svc
                            port:
                                number: 3000
